# Generated by Django 5.2.15 on 2026-08-05 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFactSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='대표 사업명 (예: 당진행복솔라)', max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='별칭 목록 — 약칭·구명칭·PJT명. 예: ["대호1차", "홍성 염해태양광"]')),
                ('spc_name', models.CharField(blank=True, default='', help_text='SPC 법인명', max_length=200)),
                ('stage', models.CharField(choices=[('dev', '개발'), ('build', '건설'), ('ops', '운영')], default='dev', help_text='현재 사업 단계 (화면 강조 기준)', max_length=10)),
                ('as_of_date', models.DateField(blank=True, help_text='기준일 — 낡은 개요는 확신에 찬 오답이 된다', null=True)),
                ('author', models.CharField(blank=True, default='', help_text='작성자', max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, help_text='{ "<section_id>": { "<field_key>": {"v": 값, "s": 확정도} } }')),
                ('schema_version', models.CharField(default='v1', max_length=20)),
                ('pjt_folder', models.CharField(blank=True, default='', help_text='RAG 적재 대상 media 하위 PJT 폴더명 (예: 당진PJT(당진행복솔라)_1단계)', max_length=300)),
                ('markdown', models.TextField(blank=True, default='', help_text='최근 발행한 마크다운 스냅샷')),
                ('published_path', models.CharField(blank=True, default='', max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fact_sheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='연결된 프로젝트 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_sheets', to='workspaces.project')),
            ],
            options={
                'verbose_name': '사업 Fact-sheet',
                'verbose_name_plural': '사업 Fact-sheet',
                'db_table': 'project_fact_sheets',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project'], name='idx_factsheet_project'), models.Index(fields=['stage'], name='idx_factsheet_stage')],
            },
        ),
    ]
