# Generated by Django 5.2.15 on 2026-08-03 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='법령명')),
                ('category', models.CharField(max_length=50, verbose_name='분류')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='풍력 사업에서의 역할')),
                ('key_articles', models.TextField(blank=True, verbose_name='주요 조문')),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH — 법령 원문 확인'), ('MEDIUM', 'MEDIUM — 2차 자료 교차확인'), ('LOW', 'LOW — 미검증, 원문 대조 필요')], default='LOW', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True, verbose_name='원문 확인일')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '관련 법령',
                'verbose_name_plural': '관련 법령',
                'db_table': 'windsite_law_reference',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocalOrdinance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sido', models.CharField(db_index=True, max_length=50, verbose_name='시·도')),
                ('sigungu', models.CharField(db_index=True, max_length=50, verbose_name='시·군·구')),
                ('energy_type', models.CharField(choices=[('WIND', '풍력'), ('SOLAR', '태양광'), ('ALL', '공통')], default='WIND', max_length=10)),
                ('target', models.CharField(choices=[('RESIDENTIAL', '주거밀집지역'), ('QUIET_FACILITY', '정온시설'), ('ROAD', '도로'), ('RAILWAY', '철도'), ('OTHER', '기타')], max_length=20, verbose_name='이격 대상')),
                ('target_detail', models.CharField(blank=True, max_length=200, verbose_name='대상 상세')),
                ('distance_m', models.PositiveIntegerField(verbose_name='이격거리(m)')),
                ('ordinance_name', models.CharField(max_length=200, verbose_name='조례명')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='조문')),
                ('exemption', models.TextField(blank=True, verbose_name='완화·예외 규정')),
                ('difficulty', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='HIGH', max_length=10)),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH — 법령 원문 확인'), ('MEDIUM', 'MEDIUM — 2차 자료 교차확인'), ('LOW', 'LOW — 미검증, 원문 대조 필요')], default='LOW', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True, verbose_name='조례 확인일')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '지자체 이격거리 조례',
                'verbose_name_plural': '지자체 이격거리 조례',
                'db_table': 'windsite_local_ordinance',
                'ordering': ['sido', 'sigungu', 'target'],
            },
        ),
        migrations.CreateModel(
            name='PermitStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='순서')),
                ('phase', models.CharField(choices=[('DEV', '개발'), ('PERMIT', '인허가'), ('BUILD', '건설'), ('OPS', '운영')], max_length=10, verbose_name='단계')),
                ('name', models.CharField(max_length=200, verbose_name='절차명')),
                ('authority', models.CharField(max_length=300, verbose_name='소관기관')),
                ('law', models.CharField(blank=True, max_length=200, verbose_name='근거 법령')),
                ('article', models.CharField(blank=True, max_length=200, verbose_name='조문')),
                ('statutory_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='법정 처리기간(일)')),
                ('depends_on', models.JSONField(blank=True, default=list, verbose_name='선행 절차')),
                ('capacity_rule', models.TextField(blank=True, verbose_name='용량별 소관 구분')),
                ('conditional_on', models.CharField(blank=True, max_length=100, verbose_name='발생 조건 키')),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH — 법령 원문 확인'), ('MEDIUM', 'MEDIUM — 2차 자료 교차확인'), ('LOW', 'LOW — 미검증, 원문 대조 필요')], default='LOW', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '인허가 절차',
                'verbose_name_plural': '인허가 절차',
                'db_table': 'windsite_permit_step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RegulationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer', models.CharField(db_index=True, max_length=100, verbose_name='레이어')),
                ('condition_key', models.CharField(max_length=100, verbose_name='조건 키')),
                ('condition_desc', models.CharField(max_length=300, verbose_name='조건 설명')),
                ('status', models.CharField(choices=[('POSSIBLE', '가능'), ('CONDITIONAL', '조건부 가능'), ('IMPOSSIBLE', '불가'), ('UNKNOWN', '확인 필요')], max_length=15, verbose_name='판정')),
                ('difficulty', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=10, verbose_name='난이도')),
                ('reason_template', models.TextField(verbose_name='판정 사유')),
                ('law', models.CharField(blank=True, max_length=200, verbose_name='법령')),
                ('article', models.CharField(blank=True, max_length=200, verbose_name='조문')),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH — 법령 원문 확인'), ('MEDIUM', 'MEDIUM — 2차 자료 교차확인'), ('LOW', 'LOW — 미검증, 원문 대조 필요')], default='LOW', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '입지 판정 규칙',
                'verbose_name_plural': '입지 판정 규칙',
                'db_table': 'windsite_regulation_rule',
                'ordering': ['layer', 'condition_key'],
                'unique_together': {('layer', 'condition_key')},
            },
        ),
        migrations.CreateModel(
            name='SiteEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_m', models.PositiveIntegerField(default=500)),
                ('capacity_mw', models.FloatField(blank=True, null=True)),
                ('sido', models.CharField(blank=True, max_length=50)),
                ('sigungu', models.CharField(blank=True, max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('POSSIBLE', '가능'), ('CONDITIONAL', '조건부 가능'), ('IMPOSSIBLE', '불가'), ('UNKNOWN', '확인 필요')], default='UNKNOWN', max_length=15)),
                ('summary', models.TextField(blank=True)),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wind_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '입지 검토 이력',
                'verbose_name_plural': '입지 검토 이력',
                'db_table': 'windsite_evaluation',
                'ordering': ['-created_at'],
            },
        ),
    ]
