# Generated by Django 6.0.8 on 2026-08-05 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='내부 키')),
                ('provider', models.CharField(choices=[('VWORLD', 'V-World 데이터 API'), ('LOCAL', '내부 적재 공간데이터(SHP)'), ('OSM', 'OpenStreetMap Overpass')], default='VWORLD', max_length=10, verbose_name='데이터 출처')),
                ('layer_id', models.CharField(db_index=True, max_length=100, verbose_name='레이어 ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='레이어 제목')),
                ('role', models.CharField(choices=[('REGULATION', '규제 저촉 판정'), ('CONTEXT', '참고 정보'), ('DISTANCE', '이격거리 산정 기초'), ('PARCEL', '필지')], default='REGULATION', max_length=15, verbose_name='역할')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='화면 분류')),
                ('name_field', models.CharField(blank=True, max_length=50, verbose_name='명칭 속성')),
                ('extra_fields', models.JSONField(blank=True, default=list, verbose_name='부가 속성')),
                ('geometry_type', models.CharField(blank=True, max_length=30, verbose_name='지오메트리')),
                ('default_status', models.CharField(choices=[('POSSIBLE', '가능'), ('CONDITIONAL', '조건부 가능'), ('IMPOSSIBLE', '불가'), ('UNKNOWN', '확인 필요')], default='CONDITIONAL', max_length=15, verbose_name='기본 판정')),
                ('default_difficulty', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', max_length=10, verbose_name='기본 난이도')),
                ('proximity_m', models.PositiveIntegerField(default=0, verbose_name='근접 판정 임계(m)')),
                ('search_margin_m', models.PositiveIntegerField(default=0, verbose_name='조회 반경 가산(m)')),
                ('law', models.CharField(blank=True, max_length=200, verbose_name='근거 법령')),
                ('article', models.CharField(blank=True, max_length=200, verbose_name='조문')),
                ('action_required', models.TextField(blank=True, verbose_name='필요 조치')),
                ('probe_status', models.CharField(blank=True, max_length=20, verbose_name='실측 상태')),
                ('probe_note', models.CharField(blank=True, max_length=300, verbose_name='실측 비고')),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH — 법령 원문 확인'), ('MEDIUM', 'MEDIUM — 2차 자료 교차확인'), ('LOW', 'LOW — 미검증, 원문 대조 필요')], default='LOW', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateField(blank=True, null=True, verbose_name='확인일')),
                ('display_order', models.PositiveIntegerField(default=100, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '규제 레이어',
                'verbose_name_plural': '규제 레이어',
                'db_table': 'windsite_regulation_layer',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SpatialDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='데이터셋 키')),
                ('name', models.CharField(max_length=200, verbose_name='데이터셋명')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='분류')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='출처 기관')),
                ('source_file', models.CharField(blank=True, max_length=300, verbose_name='원본 파일')),
                ('srs_epsg', models.IntegerField(blank=True, null=True, verbose_name='원본 좌표계 EPSG')),
                ('name_field', models.CharField(blank=True, max_length=80, verbose_name='명칭 속성')),
                ('feature_count', models.PositiveIntegerField(default=0, verbose_name='피처 수')),
                ('loaded_at', models.DateTimeField(blank=True, null=True, verbose_name='적재 일시')),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH — 법령 원문 확인'), ('MEDIUM', 'MEDIUM — 2차 자료 교차확인'), ('LOW', 'LOW — 미검증, 원문 대조 필요')], default='HIGH', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '공간데이터셋',
                'verbose_name_plural': '공간데이터셋',
                'db_table': 'windsite_spatial_dataset',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SpatialFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=300, verbose_name='명칭')),
                ('kind', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='유형')),
                ('sido', models.CharField(blank=True, max_length=50, verbose_name='시·도')),
                ('sigungu', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='시·군·구')),
                ('attrs', models.JSONField(blank=True, default=dict, verbose_name='원본 속성')),
                ('geom_wkb', models.BinaryField(verbose_name='도형(WKB)')),
                ('min_x', models.FloatField(db_index=True)),
                ('min_y', models.FloatField(db_index=True)),
                ('max_x', models.FloatField(db_index=True)),
                ('max_y', models.FloatField(db_index=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lng', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='windsite.spatialdataset')),
            ],
            options={
                'verbose_name': '공간 피처',
                'verbose_name_plural': '공간 피처',
                'db_table': 'windsite_spatial_feature',
                'indexes': [models.Index(fields=['dataset', 'min_x', 'max_x'], name='windsite_sp_dataset_e56dc0_idx'), models.Index(fields=['dataset', 'min_y', 'max_y'], name='windsite_sp_dataset_e8fac8_idx')],
            },
        ),
    ]
