# Generated by Django 6.0.8 on 2026-08-05 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0002_regulationlayer_spatialdataset_spatialfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('LAW', '법령'), ('ORDINANCE', '자치법규')], default='LAW', max_length=12, verbose_name='구분')),
                ('law_name', models.CharField(db_index=True, max_length=200, verbose_name='법령·조례명')),
                ('org', models.CharField(blank=True, max_length=100, verbose_name='지자체/소관부처')),
                ('law_id', models.CharField(blank=True, max_length=30, verbose_name='법령ID')),
                ('mst', models.CharField(blank=True, max_length=30, verbose_name='일련번호')),
                ('article_label', models.CharField(db_index=True, max_length=100, verbose_name='조문 표기')),
                ('article_no', models.CharField(blank=True, max_length=10, verbose_name='조번호')),
                ('article_sub_no', models.CharField(blank=True, max_length=10, verbose_name='가지번호')),
                ('article_title', models.CharField(blank=True, max_length=300, verbose_name='조제목')),
                ('article_text', models.TextField(blank=True, verbose_name='조문 원문')),
                ('effective_date', models.CharField(blank=True, max_length=10, verbose_name='시행일자')),
                ('promulgated_date', models.CharField(blank=True, max_length=10, verbose_name='공포일자')),
                ('source_url', models.URLField(blank=True)),
                ('via_demo_account', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='수집 일시')),
            ],
            options={
                'verbose_name': '법령 조문 원문',
                'verbose_name_plural': '법령 조문 원문',
                'db_table': 'windsite_law_article',
                'ordering': ['law_name', 'article_no'],
                'unique_together': {('law_name', 'article_label')},
            },
        ),
    ]
