# Generated by Django 6.0.8 on 2026-08-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0003_lawarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationlayer',
            name='altitude_floor_field',
            field=models.CharField(blank=True, max_length=50, verbose_name='하한고도 속성'),
        ),
    ]
