# Generated by Django 5.2.17 on 2026-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0004_regulationlayer_altitude_floor_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='localordinance',
            name='addenda',
            field=models.TextField(blank=True, verbose_name='부칙(경과조치·적용례)'),
        ),
        migrations.AddField(
            model_name='localordinance',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='조례 시행일'),
        ),
    ]
