# Generated by Django 5.2.17 on 2026-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0005_localordinance_addenda_localordinance_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='localordinance',
            name='grandfather_basis',
            field=models.CharField(blank=True, max_length=20, verbose_name='기준일 근거'),
        ),
        migrations.AddField(
            model_name='localordinance',
            name='grandfather_date',
            field=models.DateField(blank=True, null=True, verbose_name='경과조치 기준일'),
        ),
    ]
