# Generated by Django 5.2.17 on 2026-08-13 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0006_localordinance_grandfather_basis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='사업명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('sido', models.CharField(blank=True, max_length=50, verbose_name='시·도')),
                ('sigungu', models.CharField(blank=True, max_length=50, verbose_name='시·군·구')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wind_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검토 프로젝트',
                'verbose_name_plural': '검토 프로젝트',
                'db_table': 'windsite_project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SitePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='배치안명')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('turbines', models.JSONField(default=list, verbose_name='호기 좌표')),
                ('turbine_radius_m', models.PositiveIntegerField(default=500, verbose_name='발전기 검토반경(m)')),
                ('corridor_radius_m', models.PositiveIntegerField(default=100, verbose_name='연결선 검토반경(m)')),
                ('capacity_mw', models.FloatField(blank=True, null=True, verbose_name='설비용량(MW)')),
                ('permit_date', models.CharField(blank=True, max_length=10, verbose_name='발전사업허가일')),
                ('sido', models.CharField(blank=True, max_length=50, verbose_name='시·도')),
                ('sigungu', models.CharField(blank=True, max_length=50, verbose_name='시·군·구')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='저장 시점 요약')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='요약 산출 시점')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wind_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='windsite.siteproject')),
            ],
            options={
                'verbose_name': '배치안',
                'verbose_name_plural': '배치안',
                'db_table': 'windsite_plan',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='windsite_plan_unique_name')],
            },
        ),
    ]
