# Generated by Django 5.2.17 on 2026-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0009_project_energy_plan_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteplan',
            name='reviewer',
            field=models.CharField(blank=True, max_length=60, verbose_name='검토자'),
        ),
    ]
