# Generated by Django 5.2.17 on 2026-08-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0010_plan_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitstep',
            name='statutory_basis',
            field=models.CharField(blank=True, max_length=10, verbose_name='처리기간 확인 상태'),
        ),
    ]
