# Generated by Django 5.2.17 on 2026-09-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0011_permitstep_statutory_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawWindSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lng', models.FloatField(verbose_name='경도')),
                ('height_m', models.PositiveIntegerField(verbose_name='바람 고도(m)')),
                ('start', models.DateTimeField(verbose_name='자료 시작(KST)')),
                ('end', models.DateTimeField(verbose_name='자료 종료(KST)')),
                ('interval_min', models.PositiveIntegerField(default=30, verbose_name='자료 간격(분)')),
                ('stats', models.JSONField(default=dict, verbose_name='통계')),
                ('samples', models.PositiveIntegerField(default=0, verbose_name='유효 표본 수')),
                ('expected_samples', models.PositiveIntegerField(default=0, verbose_name='기대 표본 수')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 시점')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawwind_samples', to='windsite.siteplan', verbose_name='배치안')),
            ],
            options={
                'verbose_name': '재현바람장 표본',
                'verbose_name_plural': '재현바람장 표본',
                'db_table': 'windsite_rawwind',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['lat', 'lng', 'height_m'], name='windsite_ra_lat_580a85_idx')],
            },
        ),
    ]
