# Generated by Django 5.2.17 on 2026-09-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windsite', '0012_rawwindsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteplan',
            name='turbine_radius_m',
            field=models.PositiveIntegerField(default=200, verbose_name='발전기 검토반경(m)'),
        ),
    ]
