# Generated by Django 5.2.15 on 2026-06-18 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(help_text='pdf | docx | xlsx', max_length=10)),
                ('storage_uri', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('uploaded', '업로드 완료'), ('parsing', '파싱 중'), ('embedding', '임베딩 중'), ('indexed', '인덱싱 완료'), ('failed', '실패')], default='uploaded', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, help_text='NULL이면 전사 공용 코퍼스', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workspaces.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, default='', max_length=300)),
                ('char_start', models.IntegerField(blank=True, null=True)),
                ('char_end', models.IntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=200)),
                ('cell_range', models.CharField(blank=True, default='', max_length=100)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('qdrant_point_id', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': '문서 청크',
                'verbose_name_plural': '문서 청크',
                'db_table': 'document_chunks',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project'], name='idx_documents_project_dj'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_documents_status_dj'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='idx_chunks_document_dj'),
        ),
    ]
