# Generated by Django 5.2.15 on 2026-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='article_number, article_title, chunk_type 등'),
        ),
    ]
