# Generated by Django 5.2.15 on 2026-07-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_role',
            field=models.CharField(choices=[('parent', 'Parent (답변용 전체 조항)'), ('child', 'Child (검색용 세부 문장)'), ('standalone', 'Standalone (단독 청크)')], default='standalone', help_text='parent: 전체 조항(LLM용) | child: 세부 문장(검색용) | standalone: 단독', max_length=20),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document_type',
            field=models.CharField(blank=True, default='general', help_text='contract | report | financial | general', max_length=50),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='parent_chunk',
            field=models.ForeignKey(blank=True, help_text='child 청크의 경우 부모 parent 청크 참조', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='project_name',
            field=models.CharField(blank=True, default='', help_text='예: 당진 1단계, 태평, 홍성', max_length=200),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='spc_name',
            field=models.CharField(blank=True, default='', help_text='예: 당진행복솔라, 신안증도태양광', max_length=200),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='sub_type',
            field=models.CharField(blank=True, default='', help_text='예: EPC, O&M, PPA, PF', max_length=100),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_role'], name='idx_chunks_role'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['project_name'], name='idx_chunks_project'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document_type'], name='idx_chunks_doctype'),
        ),
    ]
