# Generated by Django 5.2.15 on 2026-06-18 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('use_internal_docs', models.BooleanField(default=True, help_text='사내 문서 참조 토글(대화별)')),
                ('is_shared', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='workspaces.project')),
            ],
            options={
                'verbose_name': '대화',
                'verbose_name_plural': '대화',
                'db_table': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('copy', '복사'), ('move', '이동'), ('link', '링크')], default='copy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='chat.conversation')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shared_to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_conversations', to='workspaces.project')),
            ],
            options={
                'verbose_name': '대화 공유',
                'verbose_name_plural': '대화 공유',
                'db_table': 'conversation_shares',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI'), ('system', '시스템')], max_length=12)),
                ('content', models.TextField()),
                ('used_internal_docs', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('token_usage', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '처리 중'), ('done', '완료'), ('failed', '실패')], default='done', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=10)),
                ('storage_uri', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('parsed_text_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_title', models.CharField(help_text='전체 파일명(호버 팝업)', max_length=500)),
                ('short_label', models.CharField(blank=True, default='', help_text='표시용 5자(칩)', max_length=20)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, default='', help_text='예: p.12 · 제3조', max_length=120)),
                ('score', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('document_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentchunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='chat.message')),
            ],
            options={
                'verbose_name': '메시지 출처',
                'verbose_name_plural': '메시지 출처',
                'db_table': 'message_sources',
                'ordering': ['rank'],
            },
        ),
    ]
