# Generated by Django 5.2.15 on 2026-06-18 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='JDA, SPA, SHA, EPC ...', max_length=20, unique=True)),
                ('name_ko', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('template_body', models.TextField(blank=True, default='', help_text='표준 양식(placeholder)')),
                ('key_term_schema', models.JSONField(blank=True, default=list, help_text='입력 필드 정의(라벨/타입/필수)')),
                ('standard_clauses', models.JSONField(blank=True, default=list)),
                ('review_checklist', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '표준 계약서',
                'verbose_name_plural': '표준 계약서',
                'db_table': 'contract_templates',
            },
        ),
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('source_document_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('review_instruction', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('output_file_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', '대기'), ('reviewing', '검토 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reviews', to='workspaces.project')),
                ('template', models.ForeignKey(blank=True, help_text='추정 유형', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='contracts.contracttemplate')),
            ],
            options={
                'verbose_name': '계약서 검토',
                'verbose_name_plural': '계약서 검토',
                'db_table': 'contract_reviews',
            },
        ),
        migrations.CreateModel(
            name='ContractReviewFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_ref', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(choices=[('high', '독소'), ('mid', '불리'), ('low', '경고/누락')], default='mid', max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('finding', models.TextField()),
                ('suggestion', models.TextField(blank=True, default='')),
                ('source_clause_ref', models.CharField(blank=True, default='', max_length=100)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='contracts.contractreview')),
            ],
            options={
                'verbose_name': '검토 결과',
                'verbose_name_plural': '검토 결과',
                'db_table': 'contract_review_findings',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ContractDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('key_terms', models.JSONField(blank=True, default=dict, help_text='사용자 입력 Key-term')),
                ('generated_content', models.TextField(blank=True, default='')),
                ('output_file_uri', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('draft', '초안'), ('generating', '생성 중'), ('completed', '완료'), ('failed', '실패')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_drafts', to='workspaces.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='contracts.contracttemplate')),
            ],
            options={
                'verbose_name': '계약서 초안',
                'verbose_name_plural': '계약서 초안',
                'db_table': 'contract_drafts',
            },
        ),
    ]
